name: 'snapchat_ads'
version: '0.2.0'
config-version: 2
require-dbt-version: [">=0.20.0"]
vars:
  snapchat_ads:
    creative_history: "{{ ref('stg_snapchat__creative_history') }}"
    creative_url_tag_history: "{{ ref('stg_snapchat__creative_url_tag_history') }}"
    ad_hourly_report: "{{ ref('stg_snapchat__ad_hourly_report') }}"
    ad_account_history: "{{ ref('stg_snapchat__ad_account_history') }}"
    ad_history: "{{ ref('stg_snapchat__ad_history') }}"
    ad_squad_history: "{{ ref('stg_snapchat__ad_squad_history') }}"
    campaign_history: "{{ ref('stg_snapchat__campaign_history') }}"
  dbt_utils_dispatch_list: ['spark_utils', 'fivetran_utils']
  fivetran_utils_dispatch_list: ['spark_utils']
models:
  snapchat_ads:
    +schema: snapchat_ads
    +materialized: table
